name: reactive_forms_generator_monorepo

workspace:
  - packages/generator_tests
  - packages/reactive_forms_annotations
  - packages/reactive_forms_generator
  - packages/reactive_forms_generator/example

environment:
  sdk: ">=3.8.0 <4.0.0"

dependency_overrides:
  test_api: 0.7.7

dev_dependencies:
  build_runner: ^2.10.5
  melos: ^7.3.0

melos:
  scripts:
    format:
      exec: dart format .
    gen:build:
      run: dart run build_runner build --delete-conflicting-outputs
      exec:
        orderDependents: true
      packageFilters:
        dependsOn: build_runner
        ignore: "*example*"
