name: reactive_forms_generator
description: Generator for reactive_forms. Generates form classes based on model.
repository: https://github.com/artflutter/reactive_forms_generator

version: 7.5.0-beta1

environment:
  sdk: ">=3.8.0 <4.0.0"
resolution: workspace

dependencies:
  build: ^4.0.4
  source_gen: ^4.1.2
  _fe_analyzer_shared: ^92.0.0
  analyzer: ^9.0.0
  path: ^1.9.1
  build_runner: ^2.10.5
  code_builder: ^4.11.1
  collection: ">=1.0.0 <2.0.0"
  dart_style: ^3.1.3
  recase: ^4.1.0

dev_dependencies:
  build_test: ^3.5.5
  logging: ^1.3.0
  flutter_lints: ^6.0.0
